server:
  port: 8080
  
# tag::zuul[]
spring:
  cloud:
    gateway:
      routes:
      # ========================================================
      - id: imagesService
        uri: lb://IMAGES
        predicates:
        - Path=/imagesService/**
        filters:
        - RewritePath=/imagesService/(?<segment>.*), /$\{segment}
        - RewritePath=/imagesService, /
        - SaveSession
      - id: images
        uri: lb://IMAGES
        predicates:
        - Path=/images/**
        filters:
        - SaveSession
      - id: mainCss
        uri: lb://IMAGES
        predicates:
        - Path=/main.css
        filters:
        - SaveSession
      - id: commentsService
        uri: lb://IMAGES
        predicates:
        - Path=/comments/**
        filters:
        - SaveSession
# end::zuul[]
    stream:
      bindings:
        input:
          destination: spring-social-chat
          group: comments-chat
          content-type: application/json
        newComments:
          destination: spring-social-chat
          group: comments-chat
          content-type: application/json
        clientToBroker:
          destination: spring-social-chat-user-messages
          group: app-chatMessages
        brokerToClient:
          destination: spring-social-chat-user-messages
          group: topic-chatMessages

# tag::secured[]
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
# end::secured[]

# tag::ribbon[]
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000
# end::ribbon[]
