server: 
  port: 9000

# start::settings[]
spring:
  cloud:
    stream:
      bindings:
        input:
          destination: spring-social-comments
          group: comments
          content-type: application/json        
# end::settings[]