server:
  port: 9000

security:
  sessions: never
  user:
    password: password
  
# tag::secured[]
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
# end::secured[]
  
spring:
  cloud:
    stream:
      bindings:
        input:
          destination: spring-social-comments
          group: comments-service
          content-type: application/json
        output:
          destination: spring-social-chat
          group: comments-chat
          content-type: application/json
